node-web:
  app:
    cors: true
    assets: assets
    port: 3000
    host: localhost
    viewDir: view
    controllerDir: controller
  cache:
    maxCacheSize: 104857600
    expire: 60000
  data:
    mysql:
      -
        dao: jweb-mysql
        bean: primary
        master: true
        host: 127.0.0.1
        port: 3306
        user: root
        password: 123123
        database: test
        connectionLimit: 20
